pagarme/the-office

database.rules.json
Permite a criação de novas salas usando database-rules.
=> Permite criação de novas salas

src/components/Room.svelte, src/containers/Rooms.svelte
Relates to https://github.com/lucianopf/escritorio-pagarme/issues/12
=> rooms: create globalyPinnedRoom flag

functions/index.js
Altera o funcionamento do sistema de presença para não remover o usuário da sala imediatamente, dando 2 segundos para o usuário voltar a ficar online.
Essa alteração visa corrigir um "bug" dado a uma falha de milisegundos na comunicação do websocket com o servidor do firebase e essa "micro" falha removia o usuário inesperadamente da sala.
=> Alteração no sistema de presença

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/PULL_REQUEST_TEMPLATE.md
Inserting basic files to organize the content of issues and pull requests.
=> Github: add template files

database.rules.json, functions/index.js
This PR implements a new concept of server side validation of the used domain and if its not allowed it will disable the account, mark the user data and add it to a blocked users list.
Implements https://github.com/lucianopf/escritorio-pagarme/issues/24
=> Restirct signup domains

src/models/base.js
Aims to refactor unused methods at the base model.
Closes https://github.com/lucianopf/escritorio-pagarme/issues/18
=> Refactor base model

src/containers/Rooms.svelte
Adiciona input para filtrar salas
Closes #28 
=> feature: add search rooms

src/containers/Rooms.svelte
Fix rooms filter width.
Closes #XXX 
=> rooms: fix filter width

src/components/Meet.svelte, src/components/Nav.svelte, src/components/Room.svelte, src/containers/Index.svelte, src/containers/Login.svelte, src/containers/Manage.svelte, src/containers/Rooms.svelte, src/models/base.js
Lint a bit the project trying to make it easier to view diff at Github
=> refactor: lint

README.md
Adiciona documentação do projeto e guia básico do que se trata o projeto.
Implements https://github.com/lucianopf/escritorio-pagarme/issues/14
=> Adiciona documentação

.editorconfig
Adding the file `.editorconfig` to maintain  a consistent coding style.
=> project: add .editorconfig

src/components/Nav.svelte, src/components/Room.svelte, src/containers/Index.svelte, src/containers/Manage.svelte, src/services/helpers.js, src/services/store.js
Adds a very simple routing system that will "reroute" the user to a desired room.
It will work as the following `https://escritorio.pagarme.now.sh/#/rooms/<room-slug>`
Implements https://github.com/lucianopf/escritorio-pagarme/issues/17
=> Routes system

src/containers/Rooms.svelte
Due the order system we're facing a couple problems when joining new rooms, and sometimes it conflicts the desired room
=> Fix order by users count

src/components/UserProfile.svelte
Reverts lucianopf/escritorio-pagarme#53
Reverting because it doesn't work as expected in Chrome as in Firefox
=> Revert "user-profile: refactor tooltip css"

README.md, README.pt.md, docker-compose.yml
This is a proposal to use a Docker based environment for development
only :wink:
The choice for NodeJS version is based on the current LTS, `10.16.3`.
It's always a good practice to not use your local environment for development. Things may crash if people have different dependencies installed on their machines, so an isolated environment can save time and avoid such problems :wink:
Closes #XXX 
=> proposal: add development environment

README.md, README.pt.md
=> readme: fix Miguel's username

package-lock.json, package.json
When I've installed the dependencies on my machine, this vulnerabilities showed up:
By doing a `npm audit fix`, I have been able to fix all dependencies vulnerabilities :slightly_smiling_face: 
By doing a `npm audit` now, it shows that everything has been fixed:
And yes, I have tried running the project again after the update, and it seems that nothing changed :+1: 
Closes #57 
=> package: fix dependencies vulnerabilities

database.rules.json, functions/index.js
Sometimes the firebase function doesn't work as expected, due this behavior I've created a new function (triggered by http) that traverse all users that have a value at "activeRoom" attribute, and check wether or not the user is logged in. If the user is not logged in we remove it from any pending rooms.
=> Create refresh users script

database.rules.json, src/components/CreateRoom.svelte, src/components/ManageRoom.svelte, src/containers/Manage.svelte
In order to keep the rooms list correct we must allow users to delete its own rooms.
Tasks:
=> [Feature] Delete room 

README.md
This PR adds to the readme file a simple explanation of how setup Firebase so you can test your project localy.
=> read-me: add firebase configuration to readme file

README.md, README.pt.md, src/components/Nav.svelte, src/containers/Index.svelte
Remove nav items when user is inactive. Also, it fixes some inconsistencies on readme.
=> Hide nav items when inactive

src/components/Meet.svelte
Adiciona a config  `disableAudioLevels: true` no player para "economizar" CPU
Closes #87
=> Disable audio levels to save CPU
